import type { EightDReportInput } from "../lib/eightDPdf";

/** Synthetic investigation; never reads or modifies customer data. */
export function reportFixture(method: "ishikawa" | "five_why" | "fault_tree" = "ishikawa"): EightDReportInput {
  const content = {
    D1: { champion: "Quality Manager", scope: "Service-part fulfilment and dispatch", team_members: [{ role: "Warehouse lead", responsibility: "Stock reconciliation and picking controls" }, { role: "Service manager", responsibility: "Dispatch readiness and customer communication" }] },
    D2: { summary: "A service visit was delayed because a replacement module was unavailable before dispatch, although ERP showed available stock.", what: "Replacement module unavailable", where: "Warehouse / technician dispatch", when: "12 September 2026", who: "Warehouse and field service", why_significant: "Delayed service and repeat transport", how_detected: "Pre-dispatch physical stock check", how_many: "1 affected service order" },
    D3: { customer_protection_summary: "Service rescheduled with customer agreement; similar orders checked before dispatch.", actions: [{ action: "Reconcile stock and reserve the replacement module", owner_role: "Warehouse lead", due: "2026-09-13", verification: "Physical count and reservation record" }] },
    D4: { d4_rca_methods: { ishikawa: method === "ishikawa", five_why: method === "five_why", fault_tree: method === "fault_tree" },
      ishikawa: { man: ["Pick confirmation training"], machine: ["Scanner connectivity"], method: ["No physical reservation check"], material: ["Unavailable replacement module"], measurement: ["ERP-to-bin reconciliation"], environment: ["Shift handover controls"] },
      five_why: ["The physical bin was empty at dispatch.", "ERP stock was not updated after the previous issue.", "An offline issue was not reconciled.", "The exception queue was not reviewed.", "No owner or review frequency was defined for issue exceptions."],
      fault_tree: { root: { id: "top", text: "Stale top event must not replace D2", type: "top", gate: "and", children: [
        { id: "a", text: "Physical module unavailable", type: "intermediate", gate: "or", children: [{ id: "a1", text: "Stock issued without reconciliation", type: "basic", gate: null, children: [] }, { id: "a2", text: "Reservation not physically verified", type: "basic", gate: null, children: [] }] },
        { id: "b", text: "Dispatch released without readiness check", type: "basic", gate: null, children: [] },
      ] } },
      selected_root_cause: "No physical reservation check", occurrence_root_cause: "Offline issue exceptions lacked an assigned reconciliation owner.", detection_escape_root_cause: "Dispatch relied on ERP availability without checking physical reservation.", verification_method: "Reconcile issue history and reproduce the offline exception in a controlled test.", root_cause_verification: { status: "verified", evidence: ["Stock reconciliation record SR-014", "Controlled exception test CT-022"] }, investigation_findings: [{ finding: "ERP showed stock while the physical bin was empty.", evidence_support: ["Bin count BC-011"] }], hypotheses: [], rejected_hypotheses: ["Supplier late delivery ruled out: receipt confirmed before the service order."] },
    D5: { actions: [{ root_cause: "Unowned issue exceptions", permanent_action: "Assign daily exception reconciliation and enforce physical reservation before dispatch", verification: "Controlled offline issue and readiness-check test", effectiveness_measure: "Zero unreconciled issues older than one shift" }] },
    D6: { implementation_plan: [{ step: "Release revised work instruction and train both shifts", owner_role: "Warehouse manager", due: "2026-09-18" }], validation_plan: "Review thirty consecutive service orders across both shifts.", evidence_required: ["Training register", "Thirty-order readiness review"], validation_results: [{ criterion: "Every dispatched order has a verified physical reservation", result: "30 of 30 met the criterion; no stock-related delay", evidence_reference: "Validation record VR-030" }] },
    D7: { standardization: ["Daily exception ownership embedded in the shift checklist"], documents_to_update: ["WI-WH-07 and process FMEA"], read_across: ["Apply to all service-part warehouses"], lessons_learned: "ERP availability is not a substitute for a verified physical reservation." },
    D8: { closure_summary: "Corrective actions completed and effectiveness verified; customer service restored.", recognition: "Warehouse and field-service teams recognized for coordinated containment.", approvals: [{ role: "Quality manager", name_placeholder: "Example approver" }, { role: "Service manager", name_placeholder: "Example service approver" }] },
  };
  return { caseRow: { id: "00000000-0000-4000-8000-000000000014", title: "Demo / Required spare part unavailable before technician dispatch", status: "closed", customer: "Example Manufacturing", project: "Industrial field service", product: "Replacement control module", source_reference: "CC-DEMO-014", created_at: "2026-09-12T08:00:00Z", updated_at: "2026-09-30T14:00:00Z" }, sections: Object.entries(content).map(([step_code, value]) => ({ step_code, content: value, approval_status: "approved" })), branding: null };
}
